[package]
name = "nbt-kit"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "lib"]

[[bin]]
name = "debug-nbt"

[[bin]]
name = "debug-compressed-nbt"

[features]
default = []
objc = ["dep:objc2", "dep:objc2-foundation", "dep:ctor"]

[dependencies]
flate2 = "1.1.9"

[dependencies.objc2]
version = "0.6.4"
optional = true
features = ["exception"]

[dependencies.objc2-foundation]
version = "0.3.2"
optional = true

[dependencies.ctor]
version = "1.0.13"
optional = true
